### ISSUE TITLE
官网的在线文档《任务间同步及通信》例程有一个小bug

### ISSUE THREAD

**Issue by 1428409295** [RT-Thread/rtthread-manual-doc#103]
`/* 代码清单：关闭中断进行全局变量的访问 */
#include <rtthread.h>

/* 同时访问的全局变量 */
static rt_uint32_t cnt;
void thread_entry(void* parameter)
{
    rt_uint32_t no;
    rt_uint32_t level;

    no = (rt_uint32_t) parameter;
    while(1)
    {
        /* 关闭中断 */
        level = rt_hw_interrupt_disable();
        cnt += no;
        /* 恢复中断 */
        rt_hw_interrupt_enable(level);

        rt_kprintf("thread[%d]'s counter is %d\n", no, cnt);
        rt_thread_delay(no);
    }
}

/* 用户应用程序入口 */
void rt_application_init()
{
    rt_thread_t thread;

    /* 创建t1线程 */
    thread = rt_thread_create("t1", thread_entry, (void*)10,
        512, 10, 5);
    if (thread != RT_NULL) rt_thread_startup(thread);

    /* 创建t2线程 */
    thread = rt_thread_create("t2", thread_entry, (void*)20,
        512, 20, 5);
    if (thread != RT_NULL) rt_thread_startup(thread);
}`
上面是这一章中的一个例程源码，少了个头文件**rthw.h**，缺这个头文件的话，rt_hw_interrupt_disable和rt_hw_interrupt_enable函数识别不了，无法通过编译

**Comment by 1428409295** [comment]
这一章节下面还有一个小bug
`/*
* 程序清单：静态信号量
*
* 这个例子中将创建一个静态信号量（初始值为0 ）及一个静态线程，在这个静态线程中
* 将试图采用超时方式去获取信号量，应该超时返回。然后这个线程释放一次信号量，并
* 在后面继续采用永久等待方式去获取信号量， 成功获得信号量后返回。
*/
    #include <rtthread.h>
    #include "tc_comm.h"

    /* 线程控制块及栈 */
    static struct rt_thread thread;
    static rt_uint8_t thread_stack[THREAD_STACK_SIZE];
    /* 信号量控制块 */
    static struct rt_semaphore sem;

    /* 线程入口 */
    static void thread_entry(void* parameter)
    {
        rt_err_t result;
        rt_tick_t tick;

        /* 获得当前的OS Tick */
        tick = rt_tick_get();

        /* 试图持有信号量，最大等待10个OS Tick后返回 */
        result = rt_sem_take(&sem, 10);
        if (result == -RT_ETIMEOUT)
        {
            /* 超时后判断是否刚好是10个OS Tick */
            if (rt_tick_get() - tick != 10)
            {
                tc_done(TC_STAT_FAILED);
                rt_sem_detach(&sem);
                return;
            }
            rt_kprintf("take semaphore timeout\n");
        }
        else
        {
            /* 因为没有其他地方释放信号量，所以不应该成功持有信号量，否则测试失败 */
            tc_done(TC_STAT_FAILED);
            rt_sem_detach(&sem);
            return;
        }

        /* 释放一次信号量 */
        rt_sem_release(&sem);

        /* 永久等待方式持有信号量 */
        result = rt_sem_take(&sem, RT_WAITING_FOREVER);
        if (result != RT_EOK)
        {
            /* 不成功则测试失败 */
            tc_done(TC_STAT_FAILED);
            rt_sem_detach(&sem);
            return;
        }

        /* 测试通过 */
        tc_done(TC_STAT_PASSED);
        /* 脱离信号量对象 */
        rt_sem_detach(&sem);
    }

    int semaphore_static_init()
    {
        rt_err_t result;

        /* 初始化信号量，初始值是0 */
        result = rt_sem_init(&sem, "sem", 0, RT_IPC_FLAG_FIFO);
        if (result != RT_EOK)
        {
            tc_stat(TC_STAT_END | TC_STAT_FAILED);
            return 0;
        }

        /* 初始化线程1 */
        result = rt_thread_init(&thread, "thread", /* 线程名：thread */
            thread_entry, RT_NULL, /* 线程的入口是thread_entry，参数是RT_NULL*/
            &thread_stack[0], sizeof(thread_stack), /* 线程栈thread_stack */
            THREAD_PRIORITY, 10);
        if (result == RT_EOK) /* 如果返回正确，启动线程1 */
            rt_thread_startup(&thread);
        else
            tc_stat(TC_STAT_END | TC_STAT_FAILED);

        return 0;
    }

    #ifdef RT_USING_TC
    static void _tc_cleanup()
    {
        /* 调度器上锁，上锁后，将不再切换到其他线程，仅响应中断 */
        rt_enter_critical();

        /* 执行线程脱离 */
        if (thread.stat != RT_THREAD_CLOSE)
        {
            rt_thread_detach(&thread);

            /* 执行信号量对象脱离 */
            rt_sem_detach(&sem);
        }

        /* 调度器解锁 */
        rt_exit_critical();

        /* 设置TestCase状态 */
        tc_done(TC_STAT_PASSED);
    }

    int _tc_semaphore_static()
    {
        /* 设置TestCase清理回调函数 */
        tc_cleanup(_tc_cleanup);
        semaphore_static_init();

        /* 返回TestCase运行的最长时间 */
        return 100;
    }
    /* 输出函数命令到finsh shell中 */
    FINSH_FUNCTION_EXPORT(_tc_semaphore_static, a static semaphore example);
    #else
    /* 用户应用入口 */
    int rt_application_init()
    {
        thread_static_init();

        return 0;
    }
    #endif`
这段代码最后**rt_application_init**函数里面调用的应该是**semaphore_static_init**函数

**Comment by BernardXiong** [comment]
请发PR出来吧。针对文档的git，你可以直接在github网页上修改，然后提交的时候会自动生成出一个PR出来。
