### ISSUE TITLE
pdf是如何生成的？

### ISSUE THREAD

**Issue by wming126** [RT-Thread/rtthread-manual-doc#116]
请各位大神解答一下，pdf是怎么生成的啊，如何把自己的md文档也能生成这么好的pdf文档啊。我自己也实试过，但是没有rtthread这么好，书签啊什么的都那么好，请大神多多赐教。

**Comment by aozima** [comment]
在ubuntu主机上面生成，用到的软件包和生成命令在
.travis.yml 中有说明，按那个执行就可以生成pdf文件了。

**Comment by wming126** [comment]
好的,谢谢.我试试

**Comment by wming126** [comment]
请各位大神解答一下，当我执行 ./makepdfs  脚本的时候，提示如下错误：

`Will generate pdf for the following languages:
	 assets epub mkbok Rakefile README.md stylesheets template.html title.zh.txt zh

The generation process will start now.
assets:
	Parsing preface markdown... done
	Parsing main chapters markdown... done
	Parsing appendix markdown... done
	Creating main.tex for assets... (erb):220:in `block (3 levels) in <main>': undefined local variable or method `latex' for main:Object (NameError)
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from ./latex/makepdf:202:in `block (3 levels) in <main>'
	from ./latex/makepdf:201:in `open'
	from ./latex/makepdf:201:in `block (2 levels) in <main>'
	from ./latex/makepdf:157:in `each'
	from ./latex/makepdf:157:in `block in <main>'
	from ./latex/makepdf:19:in `figures'
	from ./latex/makepdf:156:in `<main>'
`
请问这个问题怎么解决？
