### ISSUE TITLE
希望能出系统移植的指导笔记

### ISSUE THREAD

**Issue by bishuilongyuan** [RT-Thread/rtthread-manual-doc#136]
希望能出一份bsp中没有包含的内核的系统移植的指导笔记，如果人人都能够移植RT-Thread，也就不愁bsp包含的不全面了，也扫清了RT-Thread推广应用的一大障碍。类似freertos，想用的时候直接看文档自己移植一份，不再需要等到官方的bsp支持了才能使用。

**Comment by Guozhanxin** [comment]
你的意思是移植到一个新的开发板上，还是移植到一个新的芯片上呢？
