### ISSUE TITLE
52832的工程编译错误是什么情况啊，该加的文件加进去还是错误，有没有遇到够同样问题的啊

### ISSUE THREAD

**Issue by WangYZSC** [RT-Thread/rtthread-manual-doc#142]

**Comment by WangYZSC** [comment]
把改价的文件添加完以后会有这个错误：.\build\rtthread.sct(7): error: L6236E: No section matches selector - no section to be FIRST/LAST.
是会rtthread.sct里面的错误

**Comment by aozima** [comment]
发错地方了吧

**Comment by WangYZSC** [comment]
没有发错啊，就是nrf52832的rt thread系统啊，编译不通过

**Comment by WangYZSC** [comment]
没有发错啊，就是nrf52832的rt thread系统啊，编译不通过

**Comment by BernardXiong** [comment]
这个和编程指南文档有什么关系，明显错地方了
