### ISSUE TITLE
lwip实现NAT

### ISSUE THREAD

**Issue by lizhezyj** [RT-Thread/rtthread-manual-doc#172]
两个问题
(1)我下载了ipv4_nat.c，也按照说明在main.c中写了例子，但是一直没有起作用，不知道什么原因，我想把转发过来的端口返回到本地的监听端口，类似LINUX上的重定向REDIRECT，不知道怎么实现。
例子代码：
        char * argument_list0[] = {"ifconfig","e0","172.16.100.231","172.16.100.1","255.255.255.0", 0};
	cmd_ifconfig(5,argument_list0);
	
	char * argument_list1[] = {"ifconfig","e1","192.168.100.10","192.168.100.1","255.255.255.0", 0};
	cmd_ifconfig(5,argument_list1);
	
	ip_nat_entry_t new_nat_entry;
	err_t ret=0;
	struct netif *e0_in_if;
	struct netif *e1_out_if;
	e0_in_if=netif_find("e0");
	e1_out_if=netif_find("e1");
	new_nat_entry.out_if = (struct netif *)&e1_out_if;
	new_nat_entry.in_if = (struct netif *)&e0_in_if;
	IP4_ADDR(&new_nat_entry.source_net, 172,16,100,0);
	IP4_ADDR(&new_nat_entry.source_netmask, 255, 255, 255, 0);
	IP4_ADDR(&new_nat_entry.dest_net, 192, 0, 0, 0);
	IP4_ADDR(&new_nat_entry.dest_netmask, 255, 0, 0, 0);
	ret=ip_nat_add(&new_nat_entry);
(2)此外如何在lwip中的DEBUG信息打印出来，我在arch/cc.h中增加了宏定义#define LWIP_DEBUG,也在debug.h中增加了#define LWIP_DEBUG，但是板子启动后，在串口工具上没有出现任何的lwip的打印信息，不知道如何处理

**Comment by mysterywolf** [comment]
你好请到论坛提问 论坛提问很多人会回应你 https://club.rt-thread.org/index.html
