### ISSUE TITLE
求解stm32f103c8t6上直接编译不做任何修改出现硬件错误

### ISSUE THREAD

**Issue by uestczyh222** [RT-Thread/rtthread-manual-doc#67]
psr: 0x00000000
r00: 0x00000000
r01: 0x00000000
r02: 0x00000000
r03: 0x00000000
r04: 0x200018f8
r05: 0x200018f8
r06: 0x20010000
r07: 0x200018f8
r08: 0x20010000
r09: 0x00000001
r10: 0x00000000
r11: 0x00000000
r12: 0x00000000
 lr: 0x00000000
 pc: 0x00000000
hard fault on handler

bus fault:
SCB_CFSR_BFSR:0x04 IMPRECISERR

**Comment by BernardXiong** [comment]
rt-thread/bsp中stm32f1移植是针对stm32f103zet6的，其他处理器型号请自行处理，或仔细查看编程指南。
