### ISSUE TITLE
有关目录安排和用latex模板

### ISSUE THREAD

**Issue by liubenyuan** [RT-Thread/rtthread-manual-doc#71]
嗨！大家好，我是rtthread新手，有些建议：
- 能够修改并主笔写文档的应该都是资深的rtthread大牛们，所以我觉得文档使用md来写和latex来写难度应该差不多，但是latex的缺点是语法不那么直观，仅仅对数学公式有利。附件是我用之前的一个书籍模板试着整理的，大家看看怎么样，如果需要，我就全把md转为latex。这样做的好处是，首先，我们可以用离线编译（或者travis）做一个nightly build，这样大家每次都能拿到最新的文档了；其次，以后成书或者读者阅读也方便美观，便于调整版面。
- 在简介之前，我觉得应该加入单独的一章“快速上手”，给出环境的搭建，和3到4个例子。可能大部分读者都关心怎么用，而深层次的原理和订制只有慢慢学习后才能掌握

[rtthread.pdf](https://github.com/RT-Thread/rtthread-manual-doc/files/220936/rtthread.pdf)

**Comment by liubenyuan** [comment]
当然，直接用md也行啦。另外，这个工程github主页上的pdf文件在教育网下载很慢很慢。

**Comment by BernardXiong** [comment]
非常感谢。latex pdf的英文字体有些奇怪，排版好像都是居中的？

pdf、排版是比较麻烦的事情，所以后续折腾来折腾去，选择了md。选择md的一个好处是可以在github上在线浏览，可能优先考虑的还是md吧。现在的问题主要还是出在内容上
